openapi: 3.0.0
servers: []
info:
  description: |
    API de consulta e venda de eventos.
  version: "1.0.0"
  title: TicketOffice API
  contact:
    email: leonel@ticketoffice.com.br
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
- name: retrieve
  description: Metodos de consulta
- name: execute
  description: Metodos para execução
paths:  
  /third/provide/purchase/refund:
    post:
      tags:
        - execute
      summary: Executa o reembolso do ingresso
      description: Executa o reembolso do ingresso
      operationId: executeRefund
      parameters:
        - name: key
          description: Chave do parceiro
          in: header
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/refund'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/refundResponse'
  /third/provide/purchase/do:
    post:
      tags:
        - execute
      summary: Executa a venda do ingresso
      description: Executa a venda do ingresso
      operationId: executePurchase
      parameters:
        - name: key
          description: Chave do parceiro
          in: header
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/purchase'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/purchaseResponse'
  /third/provide/events:
    get:
      tags:
        - retrieve
      summary: Lista eventos
      description: Recupera os eventos com suas apresentações e assentos disponíveis para a venda.
      operationId: findEvents
      parameters:
        - name: key
          in: query
          description: Chave do parceiro
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/events'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  requestBodies:
    purchase:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/purchase_request'
      required: true
    refund:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/refund_request'
      required: true
  schemas:
    refund_request:
      type: object
      properties:
        id_event:
          type: integer
          description: Código do evento único
        id_presentation:
          type: integer
          description: Código da apresentação único
        purchase_code:
          type: string
          description: Código da venda
        id_seat:
          type: integer
          description: Código do assento
          nullable: true
    purchaseTransaction:
        type: object
        properties:
          code:
            type: string
            description: Código da transação
          seconds:
            type: integer
            description: Segundos que levou para realizar a transação
    purchaseok:
      type: object
      properties:
        code:
          type: string
          description: Código da venda
        voucher:
          type: string
          format: uri
          description: URL do PDF do voucher
        transaction:
          $ref: '#/components/schemas/purchaseTransaction'
    refundResponse:
      type: object
      properties:
          success:
            type: boolean
            description: Resposta se o reembolso foi executado
          msg:
            type: string
            description: Mensagem da resposta da venda
    purchaseResponse:
      type: object
      properties:
          success:
            type: boolean
            description: Resposta se a venda foi efetivada ou não
          msg:
            type: string
            description: Mensagem da resposta da venda
          purchase:
              $ref: '#/components/schemas/purchaseok'
    buyer_request:
        type: object
        properties:
            document:
              type: string
              description: Documento do comprador (CPF)
            name:
              type: string
              description: Nome do comprador
            email:
              type: string
              format: email
              description: E-mail do comprador
    paymentEnum:
        type: string
        enum:
          - credit
          - debit
          - money
          - boleto
    paymentMethod_request:
        type: object
        properties:
          type:
            $ref: '#/components/schemas/paymentEnum'
    seat_request:
      type: object
      properties:
        id_seat:
          type: integer
          description: Código único do assento
        id_ticket:
          type: integer
          description: Código único do tipo de ingresso
        amount:
          type: integer
          description: Valor da venda do assento
    purchase_request:
      type: object
      properties:
        id_event:
          type: integer
          description: Código do evento único
        id_presentation:
          type: integer
          description: Código da apresentação único
        seat:
          type: array
          items:
            $ref: '#/components/schemas/seat_request'
        amount_total:
          type: integer
          description: Valor total da venda
        payment_method:      
          $ref: '#/components/schemas/paymentMethod_request'
        buyer:      
          $ref: '#/components/schemas/buyer_request'
    ticket:
      type: object
      properties:
        id_event:
          type: integer
          description: Código do evento único
        id_presentantion:
          type: integer
          description: Código único da apresentação
        id_seat:
          type: integer
          description: Código único do assento
        price:
          type: integer
          description: Valor do ingresso
        allowticketoffice:
          type: integer
          description: Permite venda em modelo físico
          minimum: 0
          maximum: 1
        allowweb:
          type: integer
          description: Permite venda em modelo web
          minimum: 0
          maximum: 1
        id:
          type: integer
          description: Código único do tipo de ingresso
        type:
          type: string
          description: Nome do tipo de ingresso
        sell_sun:
          type: integer
          description: Permite venda no domingo
          minimum: 0
          maximum: 1
        sell_mon:
          type: integer
          description: Permite venda na segunda-feira
          minimum: 0
          maximum: 1
        sell_tue:
          type: integer
          description: Permite venda na terça-feira
          minimum: 0
          maximum: 1
        sell_wed:
          type: integer
          description: Permite venda na quarta-feira
          minimum: 0
          maximum: 1
        sell_thu:
          type: integer
          description: Permite venda na quinta-feira
          minimum: 0
          maximum: 1
        sell_fri:
          type: integer
          description: Permite venda na sexta-feira
          minimum: 0
          maximum: 1
        sell_sat:
          type: integer
          description: Permite venda no sabdo
          minimum: 0
          maximum: 1
    seat:
      type: object
      properties:
        id_event:
          type: integer
          description: Código do evento único
        id_presentantion:
          type: integer
          description: Código único da apresentação
        sectorName:
          type: string
          format: string
          description: Nome do setor
        name:
          type: string
          format: string
          description: Nome do assento
        id:
          type: integer
          description: Código único do assento
        numered:
          type: integer
          description: Se o assento é númerado ou não
        tickets:
          type: array
          items:
            $ref: '#/components/schemas/ticket'  
    presentation:
      type: object
      properties:
        id_event:
          type: integer
          description: Código do evento único
        id: 
          type: integer
          description: Código único da apresentação
        date:
          type: string
          format: date
          description: Data da apresentação
        hour:
          type: string
          format: string
          pattern: '^(([0-1][0-9])|([2][0-3]))h([0-5][0-9])$'
        seats:
          type: array
          items:
            $ref: '#/components/schemas/seat'
    genre:
      type: object
      properties:
        id:
          type: integer
          format: integer
        name:
          type: string
          format: string
    events:
      type: object
      properties:
        id:
          type: integer
          description: Código do evento único
        base:
          type: integer
          description: Código da base do evento
        name:
          type: string
          description: Nome do evento
        code:
          type: integer
          description: Código do evento na base do evento (não único)
        place:
          type: string
          description: Lugar do evento
        city:
          type: string
          description: Cidade do evento
        state:
          type: string
          description: Estado da cidade do evento
        state_acronym:
          type: string
          description: Estado da cidade do evento (sigla)
        image_card:
          type: string
          format: uri
          description: URI da imagem do evento
        image_big:
          type: string
          format: uri
          description: URI da imagem do evento (Tamanho grande)
        uri:
          type: string
          format: uri
          description: URI do evento para o site do parceiro
        dates:
          type: string
          description: Texto contendo a data de inicio e fim do evento em formato d/M
        genre:
          type: array
          description: Array contendo os generos do evento
          items:
            $ref: '#/components/schemas/genre'
        created: 
          type: string
          format: date-time
          description: Data de criação do evento
        amounts:
          type: string
          description: Texto contendo o menor e maior valor do evento
        minAmount:
          type: string
          description: Valor minimo do evento
          pattern: '^\s*(?:[1-9]\d{0,2}(?:\.\d{3})*|0)(?:,\d{1,2})?$'
        maxAmount:
          type: string
          description: Valor minimo do evento
          pattern: '^\s*(?:[1-9]\d{0,2}(?:\.\d{3})*|0)(?:,\d{1,2})?$'
        changed:
          type: string
          format: date-time
          description: Data de alteração do evento
        presentations:
          type: array
          items:
            $ref: '#/components/schemas/presentation'
  securitySchemes:
      key:
        type: apiKey
        name: key
        in: header